version: '3'

services:
  db:
    container_name: auth_db
    image: postgres:14
    environment:
      - POSTGRES_HOST=0.0.0.0:5432
      - POSTGRES_USER=auth_db_user
      - POSTGRES_PASSWORD=auth_db_pass
      - POSTGRES_SSLMODE=false
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3005
    