# apiVersion: v1
# kind: Secret
# metadata:
#   name: auth-secret
#   namespace: rhythmify-namespace
# type: Opaque
# data:
#   POSTGRES_PASSWORD: "auth123"
#   JWT_SECRET_KEY: "just_test_auth_service_in_microservice_app"

apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: rhythmify-namespace
type: Opaque
data:
  POSTGRES_PASSWORD: "YWRtaW4xMjM=" # "auth123" base64 encoded
  JWT_SECRET_KEY: "amVtZW50dXJlcjEtdGVzdF9hdXRob3JpemVkLWNhbGxvY2F0aW9uLWF0dGVudGlzLmFjdGl2ZS5hcHBz" # "just_test_auth_service_in_microservice_app" base64 encoded
